
services:
  mongodb:
    container_name: mongodb
    image: mongo:8 
    volumes:
      - vol-mongodb:/data/db
    ports:
      - 5011:5011
  api-exemplo:
    container_name: gestao-de-estoque
    build: ./
    environment:
      - DB_URL=mongodb://mongodb:27017/exemplo
    ports:
      - 3000:3000

volumes:
  vol-mongodb: