services:
  mongodb:
    container_name: mongodb
    image: mongo:8
    volumes:
      - vol-mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  api:
    container_name: gestao-de-estoque
    build: ./
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://mongodb:27017/gerenciarEstoque
      - APP_PORT=5011
    ports:
      - "5011:5011"
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  vol-mongodb: