apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne

  collector:
    config:
      processors:
        batch:
          timeout: 10s
      exporters:
        jaeger-thrift: {}
        spanmetrics:
          latency_buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1]
          metrics_excluded: []

  query:
    config:
      metrics-backend: prometheus
      prometheus:
        endpoint: "http://prometheus:9090"
      ui-config:
        menuEnabled: true

telemetry:
  metrics:
    level: detailed
    address: 0.0.0.0:8888
